In [2]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [99]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

## Do your thing crazy machine learning thing here :) ...

### Explore the data

In [9]:
# Show some samples
n = 5

In [10]:
print(y.shape)

(250000,)


In [11]:
print(y[:n])

[ 1. -1. -1. -1. -1.]


In [5]:
print(tX.shape)

(250000, 30)


In [12]:
print(tX[:n])

[[ 1.38470e+02  5.16550e+01  9.78270e+01  2.79800e+01  9.10000e-01
   1.24711e+02  2.66600e+00  3.06400e+00  4.19280e+01  1.97760e+02
   1.58200e+00  1.39600e+00  2.00000e-01  3.26380e+01  1.01700e+00
   3.81000e-01  5.16260e+01  2.27300e+00 -2.41400e+00  1.68240e+01
  -2.77000e-01  2.58733e+02  2.00000e+00  6.74350e+01  2.15000e+00
   4.44000e-01  4.60620e+01  1.24000e+00 -2.47500e+00  1.13497e+02]
 [ 1.60937e+02  6.87680e+01  1.03235e+02  4.81460e+01 -9.99000e+02
  -9.99000e+02 -9.99000e+02  3.47300e+00  2.07800e+00  1.25157e+02
   8.79000e-01  1.41400e+00 -9.99000e+02  4.20140e+01  2.03900e+00
  -3.01100e+00  3.69180e+01  5.01000e-01  1.03000e-01  4.47040e+01
  -1.91600e+00  1.64546e+02  1.00000e+00  4.62260e+01  7.25000e-01
   1.15800e+00 -9.99000e+02 -9.99000e+02 -9.99000e+02  4.62260e+01]
 [-9.99000e+02  1.62172e+02  1.25953e+02  3.56350e+01 -9.99000e+02
  -9.99000e+02 -9.99000e+02  3.14800e+00  9.33600e+00  1.97814e+02
   3.77600e+00  1.41400e+00 -9.99000e+02  3.21540e+01 -7.050

In [58]:
# Count nan values
# No Nan values !!! However there can be undefined values (see dataset documentation)
tX_nan_count = np.sum(np.where(tX == np.nan, 1, 0), axis = 0)
print("tX nan counts: "+str(tX_nan_count))

tX nan counts: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [40]:
def getNanStatistics(tX,axis = 0):
    print("Means: " + str(np.nanmean(tX,axis = axis)))
    print("Standard devs: " + str(np.nanstd(tX,axis = axis)))
    print("Max values: " + str(np.nanmax(tX,axis = axis)))
    print("Min values: " + str(np.nanmin(tX,axis = axis)))

In [ ]:
def plot_feature_box_plots:
    # TODO

In [8]:
np.corrcoef(tX,rowvar=False)

array([[ 1.00000000e+00, -4.55754982e-01,  1.68547985e-01,
         1.98764690e-01,  1.62660860e-01,  1.60523916e-01,
         1.62521066e-01,  2.28104685e-01,  4.58258755e-02,
         2.01464410e-01, -1.70725931e-02,  3.58962714e-01,
         1.62623001e-01,  1.31495478e-01,  2.57909175e-03,
        -6.17683359e-03,  9.94446173e-02,  1.00600077e-02,
        -7.44499050e-04, -2.33723570e-01,  7.41075286e-03,
         2.21984489e-01,  2.21077743e-01,  2.50158444e-01,
         2.47083378e-01,  2.47078209e-01,  1.62835955e-01,
         1.62613682e-01,  1.62609042e-01,  1.85371791e-01],
       [-4.55754982e-01,  1.00000000e+00,  1.90109488e-01,
        -2.49115929e-01, -1.76386051e-01, -1.90392025e-01,
        -1.75941781e-01,  4.32514093e-02,  1.77575270e-02,
        -1.46836679e-01,  3.49503614e-01, -4.19757335e-01,
        -1.76262284e-01, -1.45464145e-01, -2.10917148e-03,
         1.13208392e-03,  3.10647518e-01, -6.77706784e-03,
         3.40330242e-04,  1.83716377e-01, -1.59253407e-

In [15]:
import pandas as pd

In [ ]:
def box_plot(tX):
# TODO: box plots to see correlations

In [18]:
df = pd.read_csv(DATA_TRAIN_PATH)
display(df)

Id Prediction  DER_mass_MMC  DER_mass_transverse_met_lep  \
0       100000          s       138.470                       51.655   
1       100001          b       160.937                       68.768   
2       100002          b      -999.000                      162.172   
3       100003          b       143.905                       81.417   
4       100004          b       175.864                       16.915   
...        ...        ...           ...                          ...   
249995  349995          b      -999.000                       71.989   
249996  349996          b      -999.000                       58.179   
249997  349997          s       105.457                       60.526   
249998  349998          b        94.951                       19.362   
249999  349999          b      -999.000                       72.756   

        DER_mass_vis  DER_pt_h  DER_deltaeta_jet_jet  DER_mass_jet_jet  \
0             97.827    27.980                  0.91           124.711   
1            103.235    48.146               -999.00          -999.000   
2            125.953    35.635               -999.00          -999.000   
3             80.943     0.414               -999.00          -999.000   
4            134.805    16.405               -999.00          -999.000   
...              ...       ...                   ...               ...   
249995        36.548     5.042               -999.00          -999.000   
249996        68.083    22.439               -999.00          -999.000   
249997        75.839    39.757               -999.00          -999.000   
249998        68.812    13.504               -999.00          -999.000   
249999        70.831     7.479               -999.00          -999.000   

        DER_prodeta_jet_jet  DER_deltar_tau_lep  ...  PRI_met_phi  \
0                     2.666               3.064  ...       -0.277   
1                  -999.000               3.473  ...       -1.916   
2                  -999.000               3.148  ...       -2.186   
3                  -999.000               3.310  ...        0.060   
4                  -999.000               3.891  ...       -0.871   
...                     ...                 ...  ...          ...   
249995             -999.000               1.392  ...        2.859   
249996             -999.000               2.585  ...       -0.867   
249997             -999.000               2.390  ...       -2.890   
249998             -999.000               3.365  ...        0.811   
249999             -999.000               2.025  ...       -1.596   

        PRI_met_sumet  PRI_jet_num  PRI_jet_leading_pt  PRI_jet_leading_eta  \
0             258.733            2              67.435                2.150   
1             164.546            1              46.226                0.725   
2             260.414            1              44.251                2.053   
3              86.062            0            -999.000             -999.000   
4              53.131            0            -999.000             -999.000   
...               ...          ...                 ...                  ...   
249995        144.665            0            -999.000             -999.000   
249996         80.408            0            -999.000             -999.000   
249997        198.907            1              41.992                1.800   
249998        112.718            0            -999.000             -999.000   
249999         99.405            0            -999.000             -999.000   

        PRI_jet_leading_phi  PRI_jet_subleading_pt  PRI_jet_subleading_eta  \
0                     0.444                 46.062                    1.24   
1                     1.158               -999.000                 -999.00   
2                    -2.028               -999.000                 -999.00   
3                  -999.000               -999.000                 -999.00   
4                  -999.000               -999.000                 -999.00   
...         

In [19]:
df.describe()

Id   DER_mass_MMC  DER_mass_transverse_met_lep  \
count  250000.000000  250000.000000                250000.000000   
mean   224999.500000     -49.023079                    49.239819   
std     72168.927986     406.345647                    35.344886   
min    100000.000000    -999.000000                     0.000000   
25%    162499.750000      78.100750                    19.241000   
50%    224999.500000     105.012000                    46.524000   
75%    287499.250000     130.606250                    73.598000   
max    349999.000000    1192.026000                   690.075000   

        DER_mass_vis       DER_pt_h  DER_deltaeta_jet_jet  DER_mass_jet_jet  \
count  250000.000000  250000.000000         250000.000000     250000.000000   
mean       81.181982      57.895962           -708.420675       -601.237051   
std        40.828691      63.655682            454.480565        657.972302   
min         6.329000       0.000000           -999.000000       -999.000000   
25%        59.388750      14.068750           -999.000000       -999.000000   
50%        73.752000      38.467500           -999.000000       -999.000000   
75%        92.259000      79.169000              0.490000         83.446000   
max      1349.351000    2834.999000              8.503000       4974.979000   

       DER_prodeta_jet_jet  DER_deltar_tau_lep     DER_pt_tot  ...  \
count        250000.000000       250000.000000  250000.000000  ...   
mean           -709.356603            2.373100      18.917332  ...   
std             453.019877            0.782911      22.273494  ...   
min            -999.000000            0.208000       0.000000  ...   
25%            -999.000000            1.810000       2.841000  ...   
50%            -999.000000            2.491500      12.315500  ...   
75%              -4.593000            2.961000      27.591000  ...   
max              16.690000            5.684000    2834.999000  ...   

         PRI_met_phi  PRI_met_sumet    PRI_jet_num  PRI_jet_leading_pt  \
count  250000.000000  250000.000000  250000.000000       250000.000000   
mean       -0.010119     209.797178       0.979176         -348.329567   
std         1.812223     126.499506       0.977426          532.962789   
min        -3.142000      13.678000       0.000000         -999.000000   
25%        -1.575000     123.017500       0.000000         -999.000000   
50%        -0.024000     179.739000       1.000000           38.960000   
75%         1.561000     263.379250       2.000000           75.349000   
max         3.142000    2003.976000       3.000000         1120.573000   

       PRI_jet_leading_eta  PRI_jet_leading_phi  PRI_jet_subleading_pt  \
count        250000.000000        250000.000000          250000.000000   
mean           -399.254314          -399.259788            -692.381204   
std             489.338286           489.333883             479.875496   
min            -999.000000          -999.000000            -999.000000   
25%            -999.000000          -999.000000            -999.000000   
50%              -1.872000            -2.093000            -999.000000   
75%               0.433000             0.503000              33.703000   
max               4.499000             3.141000             721.456000   

       PRI_jet_subleading_eta  PRI_jet_subleading_phi  PRI_jet_all_pt  
count           250000.000000           250000.000000   250000.000000  
mean              -709.121609             -709.118631       73.064591  
std                453.384624              453.389017       98.015662  
min               -999.000000             -999.000000        0.000000  
25%               -999.000000             -999.000000        0.000000  
50%               -999.000000             -999.000000       40.512500  
75%                 -2.457000               -2.275000      109.933750  
max                  4.500000                3.142000     1633.433000  

[8 rows x 31 columns]

In [41]:
getNanStatistics(tX)

Means: [-4.90230794e+01  4.92398193e+01  8.11819816e+01  5.78959617e+01
 -7.08420675e+02 -6.01237051e+02 -7.09356603e+02  2.37309984e+00
  1.89173324e+01  1.58432217e+02  1.43760943e+00 -1.28304708e-01
 -7.08985189e+02  3.87074191e+01 -1.09730480e-02 -8.17107200e-03
  4.66602072e+01 -1.95074680e-02  4.35429640e-02  4.17172345e+01
 -1.01191920e-02  2.09797178e+02  9.79176000e-01 -3.48329567e+02
 -3.99254314e+02 -3.99259788e+02 -6.92381204e+02 -7.09121609e+02
 -7.09118631e+02  7.30645914e+01]
Standard devs: [406.34483401  35.34481492  40.82860887  63.65555431 454.47965615
 657.97098617 453.01897051   0.78290955  22.2734492  115.70588372
   0.84474126   1.19358245 453.59581401  22.41203584   1.21407622
   1.81675941  22.06487828   1.26497962   1.81660763  32.8946274
   1.81221908 126.49925272   0.97742435 532.96172343 489.33730734
 489.33290465 479.87453609 453.38371728 453.3881105   98.01546598]
Max values: [1.192026e+03 6.900750e+02 1.349351e+03 2.834999e+03 8.503000e+00
 4.974979e+03 1

In [9]:
df.columns

Index(['Id', 'Prediction', 'DER_mass_MMC', 'DER_mass_transverse_met_lep',
       'DER_mass_vis', 'DER_pt_h', 'DER_deltaeta_jet_jet', 'DER_mass_jet_jet',
       'DER_prodeta_jet_jet', 'DER_deltar_tau_lep', 'DER_pt_tot', 'DER_sum_pt',
       'DER_pt_ratio_lep_tau', 'DER_met_phi_centrality',
       'DER_lep_eta_centrality', 'PRI_tau_pt', 'PRI_tau_eta', 'PRI_tau_phi',
       'PRI_lep_pt', 'PRI_lep_eta', 'PRI_lep_phi', 'PRI_met', 'PRI_met_phi',
       'PRI_met_sumet', 'PRI_jet_num', 'PRI_jet_leading_pt',
       'PRI_jet_leading_eta', 'PRI_jet_leading_phi', 'PRI_jet_subleading_pt',
       'PRI_jet_subleading_eta', 'PRI_jet_subleading_phi', 'PRI_jet_all_pt'],
      dtype='object')

In [14]:
df.shape

(250000, 32)

In [12]:
df.count()

Id                             250000
Prediction                     250000
DER_mass_MMC                   250000
DER_mass_transverse_met_lep    250000
DER_mass_vis                   250000
DER_pt_h                       250000
DER_deltaeta_jet_jet           250000
DER_mass_jet_jet               250000
DER_prodeta_jet_jet            250000
DER_deltar_tau_lep             250000
DER_pt_tot                     250000
DER_sum_pt                     250000
DER_pt_ratio_lep_tau           250000
DER_met_phi_centrality         250000
DER_lep_eta_centrality         250000
PRI_tau_pt                     250000
PRI_tau_eta                    250000
PRI_tau_phi                    250000
PRI_lep_pt                     250000
PRI_lep_eta                    250000
PRI_lep_phi                    250000
PRI_met                        250000
PRI_met_phi                    250000
PRI_met_sumet                  250000
PRI_jet_num                    250000
PRI_jet_leading_pt             250000
PRI_jet_lead

In [46]:
# Check undefined values per column
undef_val_count = countUndefinedValues(tX)
print("Number of undefined values per column: " + str(undef_val_count))

Number of undefined values per column: [ 38114      0      0      0 177457 177457 177457      0      0      0
      0      0 177457      0      0      0      0      0      0      0
      0      0      0  99913  99913  99913 177457 177457 177457      0]


## Pre-processing

In [89]:
feature_cols = ['DER_mass_MMC', 'DER_mass_transverse_met_lep',
       'DER_mass_vis', 'DER_pt_h', 'DER_deltaeta_jet_jet', 'DER_mass_jet_jet',
       'DER_prodeta_jet_jet', 'DER_deltar_tau_lep', 'DER_pt_tot', 'DER_sum_pt',
       'DER_pt_ratio_lep_tau', 'DER_met_phi_centrality',
       'DER_lep_eta_centrality', 'PRI_tau_pt', 'PRI_tau_eta', 'PRI_tau_phi',
       'PRI_lep_pt', 'PRI_lep_eta', 'PRI_lep_phi', 'PRI_met', 'PRI_met_phi',
       'PRI_met_sumet', 'PRI_jet_num', 'PRI_jet_leading_pt',
       'PRI_jet_leading_eta', 'PRI_jet_leading_phi', 'PRI_jet_subleading_pt',
       'PRI_jet_subleading_eta', 'PRI_jet_subleading_phi', 'PRI_jet_all_pt']
dtypes = 15 * ["float"] + ['float-angle'] + 2 * ['float'] + ['float-angle'] \
         + ['float'] + ['float-angle'] +['float'] + ['categorical'] + (2 * ['float']\
         + ['float-angle']) * 2 + ['float']

In [297]:
class DataPreprocessor:
    def __init__(self,tX,cols,dtypes):
        assert tX.shape[1] == len(cols), "The number of columns of data does not match the number of column names"
        assert len(cols) == len(dtypes), "The number f column names must match the number of dtypes"
        self.CATEGORICAL_TYPE = 'categorical'
        self.FLOAT_TYPE = 'float'
        self.FLOAT_ANGLE_TYPE = 'float-angle'
        
        self.cols = cols
        self.dtypes = dtypes
        features = list(tX.T)
        dtypes_features = [list(x) for x in zip(dtypes, features)]
        self.data_dict = dict(zip(cols,dtypes_features))
        
    def dropFeatures(self,cols):
        for c in cols:
            self.data_dict.pop(c) 
        self.cols = list(self.data_dict.keys())
        self.dtypes = [self.data_dict.get(c)[0] for c in self.cols]
        
    def getFeatures(self, cols = None):
        if not cols:
            cols = self.cols
        features_list = self.getFeaturesList(cols)
        return np.hstack(features_list)
    
    def getFeaturesList(self,cols):
        return [self.data_dict.get(c)[1].reshape(-1,1) for c in cols]
    
    def replaceUndefVal(self,undef_orig = -999.0,undef_new = 0, cols = None):
        if not cols:
            cols = self.cols
        features = self.getFeatures(cols)    
        features = np.where(features == undef_orig, np.nan, features)
        self.updateData(cols,features)
    
    def replaceNanVal(self,val = 0, cols = None):
        if not cols:
            cols = self.cols
        features = self.getFeatures(cols)
        features = np.where(np.isnan(features), val, features)
        self.updateData(cols,features)
        
    def nanStandardize(self, cols = None):
        if not cols:
            cols = [c for c in self.cols \
                    if (self.data_dict.get(c)[0] == self.FLOAT_TYPE\
                        or self.data_dict.get(c)[0] == self.FLOAT_ANGLE_TYPE)]
            
        # Check if columns are float or float angle
        for col in cols:
            if self.data_dict.get(col)[0] != self.FLOAT_TYPE \
            and self.data_dict.get(col)[0] != self.FLOAT_ANGLE_TYPE:
                raise ValueError('Cannot standardize categorical columns')
        
        features = self.getFeatures(cols)
        mean = np.nanmean(features, axis = 0)
        std = np.nanstd(features, axis = 0)
        features = (features - mean)/std
        
        self.updateData(cols,features)
   
    def updateData(self,cols,features,dtypes_list = None):
        
        features_list = list(features.T)
        if not dtypes_list:
            dtypes_list = [self.data_dict.get(c)[0] for c in cols]
        
        dtypes_features = [list(x) for x in zip(dtypes_list, features_list)]
        update_dict = dict(zip(cols,dtypes_features))
        self.data_dict.update(update_dict)
        
    def oneHotEncode(self, cols = None):
        if not cols:
            cols = [c for c in self.cols if self.data_dict.get(c)[0] == self.CATEGORICAL_TYPE]
        
        # Check if columns are categorical
        for col in cols:
            if self.data_dict.get(col)[0] != self.CATEGORICAL_TYPE:
                raise ValueError('Cannot one hot encode non-categorical columns')
        features = self.getFeatures(cols)
        n = features.shape[0]
        idx_n = range(n)
        features_list = list(features.T.astype(np.int64))
        ohe_features_list = [np.zeros((n,len(set(x)))) for x in features_list]
        for (i,x) in enumerate(ohe_features_list): 
            x[idx_n,features_list[i]] = 1 
        features = np.hstack(ohe_features_list)
        self.dropFeatures(cols)
        
        cols_sizes_list = [(c,len(set(x))) for (c,x) in zip(cols,features_list)]
        ohe_cols = [[c+"_"+str(x) for x in range(s)] for (c,s) in cols_sizes_list]
        ohe_cols = [ohe_col for ohe_col_sublist in ohe_cols for ohe_col in ohe_col_sublist]
        dtypes_list = len(ohe_cols) * [self.CATEGORICAL_TYPE]
        
        self.cols = self.cols + ohe_cols
        self.dtypes = self.dtypes + dtypes_list
        self.updateData(ohe_cols,features,dtypes_list)
    
    def outlierRemoval()
       

In [283]:
# Test data preprocessor
idx_col_cat = 22
data_prep = DataPreprocessor(tX,feature_cols,dtypes)
data_prep.replaceUndefVal(undef_new = np.nan)
data_prep.nanStandardize()
data_prep.replaceNanVal()
tX_std = data_prep.getFeatures()

tX_wo_undef_test = np.where(tX == -999.0, np.nan, tX)
tX_wo_undef_test_std = nanStandardize(np.delete(tX_wo_undef_test,idx_col_cat,axis = 1))
tX_wo_undef_test_std = np.where(np.isnan(tX_wo_undef_test_std), 0, tX_wo_undef_test_std)
assert (np.delete(tX_std,idx_col_cat,axis = 1) == tX_wo_undef_test_std).all(),"Test failed"
print("Test Ok")

Test Ok


In [298]:
# One hot encode data
data_prep_ohe = DataPreprocessor(tX,feature_cols,dtypes)
data_prep_ohe.replaceUndefVal(undef_new = np.nan)
data_prep_ohe.nanStandardize()
data_prep_ohe.replaceNanVal()
data_prep_ohe.oneHotEncode()
tX_std_ohe = data_prep_ohe.getFeatures()

In [319]:
print(tX_std_ohe[:,[29,30,31,32]])

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [312]:
data_prep_ohe.cols

['DER_mass_MMC',
 'DER_mass_transverse_met_lep',
 'DER_mass_vis',
 'DER_pt_h',
 'DER_deltaeta_jet_jet',
 'DER_mass_jet_jet',
 'DER_prodeta_jet_jet',
 'DER_deltar_tau_lep',
 'DER_pt_tot',
 'DER_sum_pt',
 'DER_pt_ratio_lep_tau',
 'DER_met_phi_centrality',
 'DER_lep_eta_centrality',
 'PRI_tau_pt',
 'PRI_tau_eta',
 'PRI_tau_phi',
 'PRI_lep_pt',
 'PRI_lep_eta',
 'PRI_lep_phi',
 'PRI_met',
 'PRI_met_phi',
 'PRI_met_sumet',
 'PRI_jet_leading_pt',
 'PRI_jet_leading_eta',
 'PRI_jet_leading_phi',
 'PRI_jet_subleading_pt',
 'PRI_jet_subleading_eta',
 'PRI_jet_subleading_phi',
 'PRI_jet_all_pt',
 'PRI_jet_num_0',
 'PRI_jet_num_1',
 'PRI_jet_num_2',
 'PRI_jet_num_3']

In [72]:
# sel_feature_cols = ['DER_mass_MMC', 'DER_mass_transverse_met_lep',
#        'DER_mass_vis', 'DER_pt_h', 'DER_deltaeta_jet_jet', 'DER_mass_jet_jet',
#        'DER_prodeta_jet_jet', 'DER_deltar_tau_lep', 'DER_pt_tot', 'DER_sum_pt',
#        'DER_pt_ratio_lep_tau', 'DER_met_phi_centrality',
#        'DER_lep_eta_centrality', 'PRI_jet_num']

In [29]:
# def getColsIdx(cols):
#     feature_cols = ['DER_mass_MMC', 'DER_mass_transverse_met_lep',
#        'DER_mass_vis', 'DER_pt_h', 'DER_deltaeta_jet_jet', 'DER_mass_jet_jet',
#        'DER_prodeta_jet_jet', 'DER_deltar_tau_lep', 'DER_pt_tot', 'DER_sum_pt',
#        'DER_pt_ratio_lep_tau', 'DER_met_phi_centrality',
#        'DER_lep_eta_centrality', 'PRI_tau_pt', 'PRI_tau_eta', 'PRI_tau_phi',
#        'PRI_lep_pt', 'PRI_lep_eta', 'PRI_lep_phi', 'PRI_met', 'PRI_met_phi',
#        'PRI_met_sumet', 'PRI_jet_num', 'PRI_jet_leading_pt',
#        'PRI_jet_leading_eta', 'PRI_jet_leading_phi', 'PRI_jet_subleading_pt',
#        'PRI_jet_subleading_eta', 'PRI_jet_subleading_phi', 'PRI_jet_all_pt']
#     col_idx = np.arange(0,30)
#     feature_col_idx_dict = dict(zip(feature_col,col_idx))
#     if (type(cols) == str):
#         return feature_col_idx_dict.get(cols) 
#     elif (type(cols) == list):
#         return [feature_col_idx_dict.get(c) for c in cols]
#     else:
#         raise TypeError("The argument should be a list or a string")

In [57]:
# def nanStandardize(x):
#     mean = np.nanmean(x,axis = 0)
#     std = np.nanstd(x,axis = 0)
#     x =(x - mean) / std
#     return x

In [18]:
# def dropFeatures(tX,cols):
#     return tX[:,getColsIdx(cols)]

In [11]:
# def countUndefinedValues(tX,undef_value = -999.0):
#     return np.sum(tX == undef_value,axis = 0)

In [35]:
# def getRowsWithUndefIdx(tX,undef_value = -999.0):
#     undef_mat = np.where(tX == undef_value,1,0)
#     return np.where(np.sum(undef_mat, axis = 1)>0,True,False)

In [42]:
# tX_wo_undef = np.where(tX == -999.0, np.nan, tX)
# getNanStatistics(tX_wo_undef)

Means: [ 1.21858528e+02  4.92398193e+01  8.11819816e+01  5.78959617e+01
  2.40373503e+00  3.71783360e+02 -8.21688171e-01  2.37309984e+00
  1.89173324e+01  1.58432217e+02  1.43760943e+00 -1.28304708e-01
  4.58289801e-01  3.87074191e+01 -1.09730480e-02 -8.17107200e-03
  4.66602072e+01 -1.95074680e-02  4.35429640e-02  4.17172345e+01
 -1.01191920e-02  2.09797178e+02  9.79176000e-01  8.48221045e+01
 -3.27458741e-03 -1.23928255e-02  5.76794744e+01 -1.18452642e-02
 -1.58228913e-03  7.30645914e+01]
Standard devs: [ 57.29802145  35.34481492  40.82860887  63.65555431   1.74221431
 397.69658434   3.58433731   0.78290955  22.2734492  115.70588372
   0.84474126   1.19358245   0.39867861  22.41203584   1.21407622
   1.81675941  22.06487828   1.26497962   1.81660763  32.8946274
   1.81221908 126.49925272   0.97742435  60.66207397   1.78454002
   1.81337943  31.98556122   2.0317286    1.8169372   98.01546598]
Max values: [1.192026e+03 6.900750e+02 1.349351e+03 2.834999e+03 8.503000e+00
 4.974979e+03 1

## Work with reduced tX

In [49]:
# tX_reduced = dropFeatures(tX,sel_feature_columns)

In [51]:
# # Check undefined values per column
# undef_val_count = countUndefinedValues(tX_reduced)
# print("Number of undefined values per column: " + str(undef_val_count))

Number of undefined values per column: [177457      0  38114 177457 177457      0      0  99913      0 177457
  99913      0      0      0]


In [54]:
# tX_reduced_wo_undef = np.where(tX_reduced == -999.0, np.nan, tX_reduced)

In [56]:
# getNanStatistics(tX_reduced_wo_undef)

Means: [-8.21688171e-01  2.37309984e+00  1.21858528e+02  4.58289801e-01
 -1.18452642e-02  4.17172345e+01  4.92398193e+01 -1.23928255e-02
  8.11819816e+01  5.76794744e+01  8.48221045e+01  1.43760943e+00
  3.87074191e+01  4.35429640e-02]
Standard devs: [ 3.58433731  0.78290955 57.29802145  0.39867861  2.0317286  32.8946274
 35.34481492  1.81337943 40.82860887 31.98556122 60.66207397  0.84474126
 22.41203584  1.81660763]
Max values: [1.669000e+01 5.684000e+00 1.192026e+03 1.000000e+00 4.500000e+00
 2.842617e+03 6.900750e+02 3.141000e+00 1.349351e+03 7.214560e+02
 1.120573e+03 1.977300e+01 7.644080e+02 3.142000e+00]
Min values: [-18.066   0.208   9.044   0.     -4.5     0.109   0.     -3.142   6.329
  30.     30.      0.047  20.     -3.142]


In [ ]:
# def oneHotEncodeCategorical(tX,index):
    # TODO

In [7]:
# print(feature_column_idx_dict)

{'DER_mass_vis': 0, 'DER_prodeta_jet_jet': 1, 'DER_pt_tot': 2, 'PRI_jet_subleading_eta': 3, 'PRI_tau_eta': 4, 'PRI_jet_subleading_pt': 5, 'DER_mass_MMC': 6, 'DER_mass_transverse_met_lep': 7, 'PRI_tau_pt': 8, 'PRI_met_sumet': 9, 'DER_met_phi_centrality': 10, 'PRI_jet_leading_eta': 11, 'DER_pt_h': 12, 'DER_lep_eta_centrality': 13, 'PRI_met_phi': 14, 'PRI_lep_eta': 15, 'PRI_jet_all_pt': 16, 'PRI_jet_leading_pt': 17, 'PRI_jet_num': 18, 'DER_mass_jet_jet': 19, 'PRI_jet_leading_phi': 20, 'PRI_tau_phi': 21, 'PRI_jet_subleading_phi': 22, 'DER_pt_ratio_lep_tau': 23, 'PRI_met': 24, 'DER_deltar_tau_lep': 25, 'DER_sum_pt': 26, 'DER_deltaeta_jet_jet': 27, 'PRI_lep_pt': 28, 'PRI_lep_phi': 29}


In [ ]:
# columns = {"DER_mass_MMC":0,"":1,"":2,"":3,"":4,:}

## Generate predictions and save ouput in csv format for submission:

In [10]:
DATA_TEST_PATH = '' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [31]:
OUTPUT_PATH = '' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)