In [26]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [27]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../data/train.csv'  
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)
DATA_TEST_PATH = '../data/test.csv' 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

## Do your thing crazy machine learning thing here :) ...

In [28]:
from proj1_utils import *
from proj1_visualization import *
from proj1_cross_validation import *
from implementations import *

### Explore the data

In [31]:
cat_cols = [22]           # PRI_jet_num: the only categorical column
tX_num, tX_cat = split_numerical_categorical(tX,cat_cols)

In [ ]:
plt.matshow(np.corrcoef(tX_num,rowvar=False))
plt.colorbar()

In [ ]:
np.corrcoef(tX_num[:,22:25],rowvar = False)

In [ ]:
np.corrcoef(tX_num[:,25:28],rowvar = False)

In [ ]:
corr_cols = [4,6,25,26,23,24]
tX_num_uncorr = np.delete(tX_num,corr_cols,axis = 1)

In [ ]:
plt.matshow(np.corrcoef(tX_num_uncorr,rowvar=False))
plt.colorbar()

In [36]:
tX_test_num, tX_test_cat = split_numerical_categorical(tX_test,cat_cols)

In [ ]:
plt.matshow(np.corrcoef(tX_test_num,rowvar=False))
plt.colorbar()

In [ ]:
tX_test_num_uncorr = np.delete(tX_test_num,corr_cols,axis = 1)

In [ ]:
plt.matshow(np.corrcoef(tX_test_num_uncorr,rowvar=False))
plt.colorbar()

## Preprocessing

In [38]:
# Treat numerical values
best_degree = 5
#full_x_train_num_nan = replace_undef_val_with_nan(tX_num_uncorr)
full_x_train_num_nan = replace_undef_val_with_nan(tX_num)
full_x_train_num_std, train_mean, train_std = nan_standardize_fit(full_x_train_num_nan)
# full_x_train_num_valid_std = replace_nan_val_with_mean(full_x_train_num_nan_std)
full_x_train_num_valid = replace_nan_val_with_median(full_x_train_num_std)
full_x_train_num_valid = replace_iqr_outliers(full_x_train_num_valid)
# Treat categorical values
full_x_train_ohe_cat = one_hot_encode(tX_cat)
full_x_train_poly = build_poly(full_x_train_num_valid , best_degree)
full_x_train = np.hstack((full_x_train_poly,full_x_train_ohe_cat))
# Treat labels
full_y_train = y
# full_y_train = relabel_y_non_negative(y).reshape(-1,1)

In [39]:
x_train, y_train, x_val, y_val = split_data(full_x_train,full_y_train,0.8)

In [40]:
# Treat numerical values
x_test_num_nan = replace_undef_val_with_nan(tX_test_num)
x_test_num_nan_std = nan_standardize_transform(x_test_num_nan,train_mean,train_std)
# x_test_num_nan_std = nan_standardize_with_median_transform(x_test_num_nan,train_median,train_std)
x_test_num_valid_std = replace_nan_val_with_median(x_test_num_nan_std)
x_test_num_valid_std = replace_iqr_outliers(x_test_num_valid_std)
# x_test_num_valid_std = replace_nan_val_with_mean(x_test_num_nan_std)
x_test_ohe_cat = one_hot_encode(tX_test_cat)
x_test_poly = build_poly(x_test_num_valid_std , best_degree)
x_test = np.hstack((x_test_poly,x_test_ohe_cat))

In [ ]:
multiHistPlots(tX_num_uncorr)

## Test grid search

### Least squares GD

### Least squares SGD

In [ ]:
method_flag = 2
degrees = np.asarray(range(1,6))
lambdas = np.asarray([0])
best_degree, best_lambda, accuracy_score, accuracy_scores_grid = degree_lambda_grid_search(y,tX,[22],0.8,method_flag,degrees,lambdas)
print(best_degree)
print(best_lambda)
print(accuracy_score)
print(accuracy_scores_grid)

SGD(50/2000): loss=0.4999560328730805, w(0)=-1.7999494721739857e-05, w1=3.5480791707477293e-06
SGD(100/2000): loss=0.5001926794149707, w(0)=-3.399670654765714e-05, w1=1.0489958052191082e-05
SGD(150/2000): loss=0.4996817964838604, w(0)=-5.1992623872818504e-05, w1=1.3375506850854295e-05
SGD(200/2000): loss=0.49961034577844315, w(0)=-7.198936799854934e-05, w1=2.36637956134491e-05
SGD(250/2000): loss=0.5003647068815094, w(0)=-8.39825402078926e-05, w1=2.823389416660846e-05
SGD(300/2000): loss=0.49992163320844546, w(0)=-0.00010997139578886805, w1=3.3456361532792676e-05
SGD(350/2000): loss=0.49938066192564445, w(0)=-0.0001299581496448557, w1=3.814024383261656e-05
SGD(400/2000): loss=0.4995744662692441, w(0)=-0.00014594592209955548, w1=3.7837670888478076e-05
SGD(450/2000): loss=0.5005391964889622, w(0)=-0.00015792810810679348, w1=4.704865296964899e-05
SGD(500/2000): loss=0.5001973942162212, w(0)=-0.00017790936626798227, w1=5.55638469687169e-05
SGD(550/2000): loss=0.5000674954478292, w(0)=-0.00

SGD(350/2000): loss=0.49802377980740137, w(0)=-9.976946632167817e-05, w1=5.3045904682887175e-05
SGD(400/2000): loss=0.4985549066697162, w(0)=-0.00011368578373648375, w1=5.8173611147130814e-05
SGD(450/2000): loss=0.5001220725584077, w(0)=-0.00012760792876787393, w1=6.941220978822826e-05
SGD(500/2000): loss=0.49617258762761807, w(0)=-0.0001454994499132223, w1=7.057521877947946e-05
SGD(550/2000): loss=0.5011661275757886, w(0)=-0.0001553972033067043, w1=7.806323806288272e-05
SGD(600/2000): loss=0.49545429233765625, w(0)=-0.0001692830815274375, w1=8.32657790262584e-05
SGD(650/2000): loss=0.5018283159412038, w(0)=-0.0001871594960338809, w1=8.656123624170673e-05
SGD(700/2000): loss=0.4951778131186983, w(0)=-0.00020102646223981588, w1=8.914234176609244e-05
SGD(750/2000): loss=0.493698591206773, w(0)=-0.00020686978903618468, w1=9.116747917620688e-05
SGD(800/2000): loss=0.5071827756469156, w(0)=-0.00021869831090553265, w1=0.00010180492886650803
SGD(850/2000): loss=0.4933540814078508, w(0)=-0.000

### Least squares

In [51]:
method_flag = 3
degrees = np.asarray(range(1,11))
lambdas = np.asarray([0])
best_degree, best_lambda, accuracy_score, accuracy_scores_grid = degree_lambda_grid_search(y,tX,[22],0.8,method_flag,degrees,lambdas)
print(best_degree)
print(best_lambda)
print(accuracy_score)
print(accuracy_scores_grid)

1
0
0.6566
[[0.6566]
 [0.3434]
 [0.3434]
 [0.3434]
 [0.6566]
 [0.6566]
 [0.6566]
 [0.3434]
 [0.3434]
 [0.6566]]


### Ridge regression

In [49]:
method_flag = 4
degrees = np.asarray(range(1,10))
lambdas = np.logspace(-10,0,11)
best_degree, best_lambda, accuracy_score, accuracy_scores_grid = degree_lambda_grid_search(y,tX,[22],0.8,method_flag,degrees,lambdas)
print(best_degree)
print(best_lambda)
print(accuracy_score)
print(accuracy_scores_grid)

7
1e-05
0.81796
[[0.7472  0.7472  0.7472  0.7472  0.7472  0.7472  0.74716 0.74722 0.74524
  0.7368  0.7141 ]
 [0.7976  0.7976  0.7976  0.7976  0.7976  0.79758 0.79764 0.79778 0.79572
  0.78564 0.7342 ]
 [0.81312 0.81312 0.81312 0.81312 0.81316 0.81308 0.81294 0.81306 0.80954
  0.79208 0.74434]
 [0.81652 0.81652 0.81652 0.81652 0.8166  0.81652 0.8163  0.8158  0.8109
  0.79326 0.75144]
 [0.81682 0.81682 0.8168  0.81688 0.817   0.81688 0.81668 0.81608 0.81152
  0.7954  0.75406]
 [0.8169  0.8169  0.8169  0.8169  0.817   0.817   0.81724 0.81592 0.81226
  0.79798 0.757  ]
 [0.81764 0.81766 0.81772 0.81776 0.8177  0.81796 0.8177  0.8162  0.81238
  0.7986  0.75744]
 [0.81658 0.8166  0.81656 0.8165  0.8172  0.81764 0.81724 0.81626 0.81274
  0.79916 0.75818]
 [0.81654 0.81656 0.81668 0.81678 0.81752 0.81786 0.81766 0.81642 0.81342
  0.8     0.75708]]


## Explore feature 12: Det_met_phi_centrality

## Ridge regression

In [ ]:
# lambdas = np.logspace(-10, 0, 20)
# k_fold = 4 
# seed = 7
# best_lambda, lambda_rmse_tr, lambda_rmse_te = cross_validation_ridge_reg_best_lambda(y_train, x_train, lambdas, k_fold, seed)

In [ ]:
# best degree 17 already found
# lambdas = [0.0000001]
# degrees = np.arange(1,20)
# seed = 7
# best_degree, best_lambda, deg_lambda_rmse_tr, deg_lambda_rmse_te = cross_validation_ridge_reg_best_degree_best_lambda(y_train, x_train, degrees, lambdas, k_fold, seed)

In [ ]:
# plt.plot(degrees,deg_lambda_rmse_tr,label = 'train error')
# plt.plot(degrees,deg_lambda_rmse_te,label = 'test error')
# plt.grid()
# plt.legend(loc = 2)
# plt.show()

In [ ]:
# print(best_degree)
# print(best_lambda)

In [ ]:
# plt.semilogx(lambdas,lambda_rmse_tr,label = 'train error')
# plt.semilogx(lambdas,lambda_rmse_te,label = 'test error')
# # plt.plot(lambdas,rmse_tr,label = 'train error')
# # plt.plot(lambdas,rmse_te,label = 'test error')
# plt.grid()
# plt.legend(loc = 2)
# plt.show()

In [ ]:
# print(best_lambda)

In [41]:
best_lambda = 1e-5
lambda_ = best_lambda
weights, loss = ridge_regression(y_train,x_train,lambda_)

## Least squares

In [ ]:
# weights = least_squares(y_train,x_train)

## Generate predictions and save ouput in csv format for submission:

In [42]:
y_pred = predict_labels(weights, x_val)
y_val = relabel_y_negative(y_val)

In [43]:
# Just to check
from sklearn.metrics import confusion_matrix,accuracy_score, f1_score, recall_score, precision_score
print(confusion_matrix(y_val,y_pred))
print(accuracy_score(y_val,y_pred))
print(f1_score(y_val,y_pred))
print(recall_score(y_val,y_pred))
print(precision_score(y_val,y_pred))

[[29050  3720]
 [ 5552 11678]]
0.81456
0.7158268971435577
0.677771329077191
0.7584101831406677


In [44]:
get_label_y_counts(y_pred)

(array([-1.,  1.]), array([34602, 15398]))

In [46]:
OUTPUT_PATH = '../results/ridge_reg_submission.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, x_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)